name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        uses: c-hive/gha-npm-cache@v1
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
